language: node_js
node_js:
  - "node" # Latest stable Node.js release

script:
  - npm run lint

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./src/
  on:
    branch: master
